const CONVERSATION_TYPE = {
    SAVE: 'SAVE',
    PRIVATE: 'PRIVATE',
    GROUP: 'GROUP',
    CHANNEL: 'CHANNEL'
}

const CONVERSATION_TYPES = Object.values(CONVERSATION_TYPE);

const ROLE = {
    OWNER: 'OWNER',
    ADMIN: 'ADMIN',
    USER: 'USER',
}

const ROLES = Object.values(ROLE);

const OPERATION = {
    DELETE_CONVERSATION: 'DELETE_CONVERSATION',
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_DESCRIPTION: 'CHANGE_DESCRIPTION',
    CHANGE_AVATAR: 'CHANGE_AVATAR',
    ADD_MEMBER: 'ADD_MEMBER',
    REMOVE_MEMBER: 'REMOVE_MEMBER',
    SET_MEMBER_ROLE_TO_OWNER: 'SET_MEMBER_ROLE',
    SET_MEMBER_ROLE_TO_ADMIN: 'SET_MEMBER_ROLE',
    SET_MEMBER_ROLE_TO_USER: 'SET_MEMBER_ROLE',
    LEAVE: 'LEAVE',
    ADD_MESSAGE: 'ADD_MESSAGE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',
    UPDATE_MESSAGE: 'EDIT_MESSAGE',
    REMOVE_OWN_MESSAGE: 'REMOVE_OWN_MESSAGE',
    UPDATE_OWN_MESSAGE: 'EDIT_OWN_MESSAGE'
}

const PERMISSIONS = {
    [ROLE.OWNER]: [
        OPERATION.DELETE_CONVERSATION,
        OPERATION.CHANGE_NAME,
        OPERATION.CHANGE_DESCRIPTION,
        OPERATION.CHANGE_AVATAR,
        OPERATION.ADD_MEMBER,
        OPERATION.REMOVE_MEMBER,
        OPERATION.SET_MEMBER_ROLE_TO_OWNER,
        OPERATION.SET_MEMBER_ROLE_TO_ADMIN,
        OPERATION.SET_MEMBER_ROLE_TO_USER,
        OPERATION.ADD_MESSAGE,
        OPERATION.REMOVE_MESSAGE,
        OPERATION.REMOVE_OWN_MESSAGE,
        OPERATION.UPDATE_OWN_MESSAGE
    ],
    [ROLE.ADMIN]: [
        OPERATION.CHANGE_NAME,
        OPERATION.CHANGE_DESCRIPTION,
        OPERATION.CHANGE_AVATAR,
        OPERATION.ADD_MEMBER,
        OPERATION.REMOVE_MEMBER,
        OPERATION.SET_MEMBER_ROLE_TO_ADMIN,
        OPERATION.SET_MEMBER_ROLE_TO_USER,
        OPERATION.ADD_MESSAGE,
        OPERATION.REMOVE_MESSAGE,
        OPERATION.REMOVE_OWN_MESSAGE,
        OPERATION.UPDATE_OWN_MESSAGE
    ],
    [ROLE.USER]: [
        OPERATION.LEAVE,
        OPERATION.ADD_MESSAGE,
        OPERATION.REMOVE_OWN_MESSAGE,
        OPERATION.UPDATE_OWN_MESSAGE
    ],
}
module.exports = {
    CONVERSATION_TYPE,
    CONVERSATION_TYPES,
    ROLE,
    ROLES,
    OPERATION,
    PERMISSIONS
}