const APIResponse = require('./APIResponse');
const RESP = {
    INVALID_USERNAME: APIResponse.badRequest("Invalid username"),
    INVALID_CREDENTIALS: APIResponse.forbidden("Invalid credentials"),
    INVALID_EMAIL: APIResponse.badRequest("Invalid Email"),
    INVALID_CONVERSATION_TYPE: APIResponse.badRequest("Invalid conversation type"),
    USERNAME_EXISTS: APIResponse.conflict("Username already exists"),
    EMAIL_EXISTS: APIResponse.conflict("Email already exists"),
    USER_EXISTS: APIResponse.conflict("User already exists"),
    USER_NOT_FOUND: APIResponse.notFound("User not found"),
    USERS_NOT_FOUND: APIResponse.notFound("One or more usernames are not users"),
    CREATED: APIResponse.created(),
    CONVERSATION_NOT_FOUND: APIResponse.notFound("Conversation not found"),
    CONVERSATION_DELETED: APIResponse.success("Conversation deleted"),
    CONVERSATION_EXISTS: APIResponse.conflict("Conversation already exists"),
    CONVERSATION_CREATED: APIResponse.success("Conversation created"),
    NOT_MEMBER: APIResponse.forbidden("You are not a member of this conversation"),
    NOT_OWNER: APIResponse.forbidden("You are not the owner of this conversation"),
    NOT_OWNER_ADMIN: APIResponse.forbidden("Only owners and admins can perform this operation"),
    NO_PERMISSION: APIResponse.forbidden("You don't have permission to perform this operation"),
    MEMBER_EXISTS: APIResponse.conflict("Username is already a member"),
    MEMBER_NOT_FOUND: APIResponse.notFound("Member not found"),
    MEMBER_DELETED: APIResponse.success("Member deleted"),
    MEMBER_ROLE_EDITED: APIResponse.success("Member role edited"),
    CONTACT_EXISTS: APIResponse.conflict("Contact already exists"),
    CONTACT_NOT_FOUND: APIResponse.notFound("Contact not found"),
    CONTACT_DELETED: APIResponse.success("Contact deleted"),
    MESSAGE_NOT_FOUND: APIResponse.notFound("Message not found"),
    MESSAGE_ADDED: APIResponse.created(),
    MESSAGE_DELETED: APIResponse.success("Message deleted"),
    MESSAGE_UPDATED: APIResponse.success("Message updated"),
    AVATAR_URL_UPDATED: APIResponse.success("Avatar URL updated"),
}

module.exports = RESP;